package com.selimhorri.app.service.impl;

import java.util.List;
import java.util.stream.Collectors;
import javax.transaction.Transactional;
import org.springframework.stereotype.Service;
import com.selimhorri.app.dto.response.VerificationTokenResponseDto;
import com.selimhorri.app.exception.wrapper.VerificationTokenNotFoundException;
import com.selimhorri.app.helper.VerificationTokenMapper;
import com.selimhorri.app.repository.VerificationTokenRepository;
import com.selimhorri.app.service.VerificationTokenService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Service
@Transactional
@Slf4j
@RequiredArgsConstructor
public class VerificationTokenServiceImpl implements VerificationTokenService {

	private final VerificationTokenRepository verificationTokenRepository;

	@Override
	public List<VerificationTokenResponseDto> findAll() {
		log.warn("*** WARNING: Fetching all verification tokens is a security risk! ***");
		return this.verificationTokenRepository.findAll()
				.stream()
				.map(VerificationTokenMapper::toResponseDto)
				.collect(Collectors.toUnmodifiableList());
	}

	@Override
	public VerificationTokenResponseDto findById(final Integer verificationTokenId) {
		log.warn("*** WARNING: Fetching a verification token by ID can be a security risk! ***");
		return this.verificationTokenRepository.findById(verificationTokenId)
				.map(VerificationTokenMapper::toResponseDto)
				.orElseThrow(() -> new VerificationTokenNotFoundException(
						String.format("VerificationToken with id: %d not found!", verificationTokenId)));
	}

	@Override
	public void create() {
		throw new UnsupportedOperationException(
				"Creating verification tokens via API is not allowed. They are generated by system processes like registration.");
	}

	@Override
	public void update() {
		throw new UnsupportedOperationException("Updating verification tokens is not allowed.");
	}

	@Override
	public void deleteById(final Integer verificationTokenId) {
		throw new UnsupportedOperationException(
				"Deleting verification tokens via API is not allowed. They are handled by system processes.");
	}

}