CREATE TABLE address (
    address_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    full_address VARCHAR(255),
    postal_code VARCHAR(255),
    city VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_AddressUser FOREIGN KEY (user_id) REFERENCES users(user_id)
);