name: 'Build Release on New Tag'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    uses: EcommerceDevops/workflows/.github/workflows/build-push-java.yml@main # Ajusta la ruta a tu archivo
    with:
      IMAGE_NAME: 'user-service-ecommerce-boot'
      JAVA: true
      
      PROJECT_VERSION: ${{ github.ref_name }}
      
    secrets: inherit