name: build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  java-build:
    uses: EcommerceDevops/workflows/.github/workflows/build-push-java.yml@main
    with:
      IMAGE_NAME: user-service-ecommerce-boot
      JAVA: true
      PROJECT_VERSION: ${{ github.ref_name }}
    secrets: inherit
