name: Manual Helmfile Update Trigger

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Nombre del servicio (ej. user-service)'
        required: true
        type: choice
        options:
        - user-service
        - shipping-service
        - proxy-client
        - product-service
        - payment-service
        - order-service
        - favourite-service
        - api-gateway
        - cloud-config
        - service-discovery
      image_tag:
        description: 'Versión del tag de la imagen (ej. v2.0.4)'
        required: true
        type: string
        
jobs:
  call-update-workflow:
    # ✅ La llamada al workflow reutilizable se hace aquí, a nivel del job.
    # Se eliminaron las claves `runs-on` y `steps`.
    uses: EcommerceDevops/workflows/.github/workflows/helmfile-versions@main
    with:
      # Estos valores se toman de los inputs del formulario manual
      service_name: ${{ github.event.inputs.service_name }}
      image_tag: ${{ github.event.inputs.image_tag }}
    secrets:
      # Asegúrate que el nombre del secreto (`GH_TOKEN`) coincida con el que espera el workflow llamado
      GH_TOKEN: ${{ secrets.WORKFLOW_PAT_ADMIN }}